models/user.py
from models.base import Base
from sqlalchemy import Integer, String, Text, DateTime, Enum, func
from sqlalchemy.orm import mapped_column, relationship, backref
from sqlalchemy.sql import func

from flask_login import UserMixin
import bcrypt


class User(Base, UserMixin):
    __tablename__ = 'user'

    id = mapped_column(Integer, primary_key = True, autoincrement=True)
    username = mapped_column (String(255), nullable=False)
    email = mapped_column (String(255), nullable=False)
    password = mapped_column (String(255), nullable=False)
    created_at = mapped_column (DateTime(timezone=True), default=func.now())
    updated_at = mapped_column (DateTime(timezone=True), default=func.now())
    role = mapped_column (Enum('User', 'Admin'), nullable=True, default=None)

    def __repr__(self):
        return f'<User {self.username}>'

    def set_password(self, password):
        self.password = bcrypt.hashpw( password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')

    def check_password(self, password):
            return bcrypt.checkpw(password.encode('utf-8'), self.password.encode('utf-8'))

controllers/user.py
from flask import Blueprint, render_template, request, redirect
from connectors.mysql_connector import engine

from models.user import User
from sqlalchemy import select, or_
from sqlalchemy.orm import sessionmaker
from flask_login import login_user, logout_user, current_user

user_routes = Blueprint('user_routes',__name__)

@user_routes.route("/register", methods=['GET'])
def user_register():
    return render_template("auth/register.html")

@user_routes.route("/register", methods=['POST'])
def do_registration():

    username = request.form['username']
    email = request.form['email']
    password = request.form['password']

    NewUser = User(username=username, email=email)
    NewUser.set_password(password)

    connection = engine.connect()
    Session = sessionmaker(connection)
    session=Session()

    session.begin()

    try:
        # session.add(NewUser)
        # session.commit()

        # user = session.query(User).filter(User.email==request.form['email']).first()

        
        session.add(NewUser)
        session.commit()

        #Check registered email
        # if user.email(request.form['email']):
        #     return {'message': 'Email already registered'}

        # # return {'message': 'Sukses register'}
        # return redirect('/login')

    except Exception as e:
        session.rollback()
        return {'message': 'Gagal Register'}
        # return e
    
    # return {'message': 'Sukses register'}
    return redirect('/login')

@user_routes.route("/login", methods=['GET'])
def user_login():
    return render_template("auth/login.html")

@user_routes.route("/login", methods=['POST'])
def do_user_login():

    response_data = dict()

    connection = engine.connect()
    Session = sessionmaker(connection)
    session=Session()

    try:
        user = session.query(User).filter(User.email==request.form['email']).first()

        if user == None:
            return {'message': 'Email tidak terdaftar'}

        #Check password
        if not user.check_password(request.form['password']):
            return {'message': 'Password salah'}
        

        login_user(user, remember=False)

        response_data['id'] = current_user.id

        
        return redirect ('/users')

        
    except Exception as e:
        return { 'message' : 'Login failed'}
        # return str(e)
    
@user_routes.route("/logout", methods=['GET'])
def do_user_logout():
    logout_user()
    return redirect('/login')

controllers/user_all.py
from flask import Blueprint, render_template, request
from connectors.mysql_connector import Session

from models.user import User
from sqlalchemy import select, or_

from decorators.role_checker import role_required
from flask_login import current_user, login_required, login_user

users_routes = Blueprint('users_routes', __name__)

@users_routes.route('/users', methods=['GET'])
@login_required
def list_users():
    response_data = dict()

    session = Session()

    try:
        user_query = select(User)

        #Tambahkan filter apabila ada search query
        if request.args.get('query') != None:
            search_query = request.args.get('query')
            user_query = user_query.where(or_(User.username.like(f'% {search_query} %'), User.email.like(f'%{search_query}%'))) 

        users= session.execute(user_query)
        users= users.scalars()
        response_data['users'] = users
        


        # print(users)
    except Exception as e:
        print(e)
        return 'Error Processing Data'

    response_data['username'] = current_user.username
    return render_template('users/user_all.html', response_data = response_data)

# User detail
@users_routes.route('/users/<id>', methods=['GET'])
@login_required
def user_detail(id):
    response_data = dict()

    session = Session()

    try:
        user = session.query(User).filter((User.id==id)).first()
        if (user == None):
            return "Data not found"
        response_data['user'] = user
    except Exception as e:
        print(e)
        return "Error Processing Data"

    response_data['id'] = current_user.id
    response_data['username'] = current_user.username
    response_data['email'] = current_user.email
    response_data['created_at'] = current_user.created_at

    return render_template("users/user_detail.html", response_data = response_data)

#User dashboard after login

@users_routes.route('/users/me', methods=['GET'])
def user_me(id):
    response_data = dict()

    session = Session()

    try:
        user = session.query(User).filter((User.id==id)).first()
        if (user == None):
            return "Data not found"
        response_data['user'] = user
    except Exception as e:
        print(e)
        return "Error Processing Data"

    login_user(user, remember=False)

    response_data['id'] = current_user.id

    return render_template("users/user_detail.html", response_data = response_data)

# Create User
@users_routes.route('/users', methods=['POST'])

def user_insert():
    new_user = User(
        username = request.form['username'],
        email = request.form['email'],
        password = request.form['password']
        )
    
    session = Session()
    session.begin()
    try:
       session.add(new_user)
       session.commit()

        
    except Exception as e:
        #Operation failed
       session.rollback()
       print(e)
       return { 'message': 'Insert data gagal'}

    #Operation sukses
    return {'message': 'Input data sukses'}


@users_routes.route('/users/<id>', methods=['DELETE'])
@role_required('Admin')
def user_delete(id):
    session = Session()
    session.begin()

    try:
        user_to_delete = session.query(User).filter(User.id==id).first()
        session.delete(user_to_delete)
        session.commit()

    except Exception as e:
        session.rollback()
        print(e)
        return{'message': 'Delete Data Gagal'}

    #Operation sukses
    return {'message': 'Delete Data Sukses'}


@users_routes.route('/users/<id>', methods=['PUT'])
@login_required
def user_update(id):
    session = Session()
    session.begin()

    try:
        user_to_update = session.query(User).filter(User.id==id).first()
        
        user_to_update.username = request.form['username']
        user_to_update.email = request.form['email']
        user_to_update.password = request.form['password']

        session.commit()

    except Exception as e:
        session.rollback()
        print(e)
        return{'message': 'Update Data Gagal'}

    #Operation sukses
    return {'message': 'Update Data Sukses'}

templates/users/user_all.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Users List</title>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
        button {
            padding: 5px 10px;
            cursor: pointer;
        }

        .search-container {
            margin-top: 20px;
        }
        
        .search-input {
            padding: 10px;
            width: 300px;
            border-radius: 5px;
            border: 1px solid #ccc;
            font-size: 16px;
        }
        
        .search-button {
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
        }
    </style>
</head>
<body>
    <div>
        Hello, {{ response_data['username'] }}
        <a href="/logout">Logout</a>
    </div>
    <h2>Users List</h2>
    <button onclick="openNewUserForm()">Add New User</button>
    <div class="search-container">
        <input type="text" class="search-input" id="searchInput" placeholder="Search...">
        <button class="search-button" onclick="search()">Search</button>
    </div>
    <hr style="border:none;"/>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Member since</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for user in response_data['users'] %}            
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.username}}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.created_at }}</td>
                <td>
                    <a href="{{ url_for('users_routes.user_detail', id=user.id) }}">User detail</a>
                    <button onclick="openEditUserForm()">Edit</button>
                    <button id="delete_{{ user.id }}" onclick="userDelete(this)">Delete</button>
                </td>
            </tr>
            {% endfor %}
            <!-- Add more <tr> elements for additional products -->
        </tbody>
    </table>

    <div id="newUserForm" style="display: none;">
        <h3 id="formSection">Add New User</h3>
        <form id="userForm">
            <label for="userName">User Name:</label>
            <input type="text" id="userName" name="userName"><br><br>
            <label for="userEmail">Email:</label>
            <input type="text" id="userEmail" name="userEmail"><br><br>
            <label for="userPassword">Password:</label>
            <input type="password" id="userPassword" name="userPassword"><br><br>
            <button type="button" onclick="submitForm()">Submit</button>
            <button type="button" onclick="closeNewUserForm()">Cancel</button>
        </form>
    </div>
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <script>
        var form_url = "";
        var form_method = "";
        var base_url = "{{ url_for('users_routes.list_users') }}";
        
        function openNewUserForm() {
            form_method = 'POST';
            form_url = base_url;
            document.getElementById("newUserForm").style.display = "block";
            document.getElementById("formSection").innerHTML = "Add New User";
            document.getElementById("userForm").reset();
        }

        function openEditUserForm(button) {
            var selected_user_id = button.id.split("_")[1];
            form_method = 'PUT';
            form_url = base_url + "/" + selected_userid;

            var name = $('#username'+selected_user_id).html();
            var email = $('#email'+selected_user_id).html();
            var pass = $('#password_'+selected_user_id).html();

            $('#userUsername').val(username);
            $('#userEmail').val(email);
            $('#userPassword').val(password);

            document.getElementById("newUserForm").style.display = "block";
            document.getElementById("formSection").innerHTML = "Edit User";
        }

        function closeNewUserForm() {
            document.getElementById("newUserForm").style.display = "none";
        }

        function submitForm(){
            var request_data = {
                name: $('#userName').val(),
                email: $('#UserEmail').val(),
                password: $('#UserPassword'). val()
            }

            $.ajax({
                url: form_url,
                data: request_data,
                method: form_method
            }).done(function(response){
                alert(response.message);
                location.reload();
            })
        }

        function userDelete(button){
            var selected_user_id = button.id.split("_")[1];
            var delete_url = base_url + "/" + selected_user_id

            $.ajax({
                url: delete_url,
                method: "DELETE"
            }).done(function(response){
                alert(response.message);
                location.reload();
            })
        }

        function search(){
            window.location = base_url + '?query=' + $('#searchInput').val();
        }
    </script>
</body>
</html>

templates/users/user_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Detail</title>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
        button {
            padding: 5px 10px;
            cursor: pointer;
        }

        .search-container {
            margin-top: 20px;
        }
        
        .search-input {
            padding: 10px;
            width: 300px;
            border-radius: 5px;
            border: 1px solid #ccc;
            font-size: 16px;
        }
        
        .search-button {
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
        }
    </style>
</head>
<body>
    <div>
        Hello, {{ response_data['username'] }}
        <a href="/logout">Logout</a>
    </div>

    <br>
    <h2>User Detail</h2>

    <p>User ID: {{ response_data['user'].id }}</p>

    <p>User Name: {{ response_data['user'].username }}</p>

    <p>User Email: {{ response_data['user'].email}}</p>

    <p>Member since: {{ response_data['user'].created_at}}</p>

    <br>
    <br>

    <h2>Account</h2>

    <p>User ID: {{ response_data['user'].id }}</p>

    <p>User Name: {{ response_data['user'].username }}</p>

    <p>User Email: {{ response_data['user'].email}}</p>

    <p>Member since: {{ response_data['user'].created_at}}</p>

    <br>


    <button onclick="openNewUserForm()">Add New User</button>
    <div class="search-container">
        <input type="text" class="search-input" id="searchInput" placeholder="Search...">
        <button class="search-button" onclick="search()">Search</button>
    </div>
    <hr style="border:none;"/>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Member since</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <!-- {% for user in response_data['users'] %}             -->
            <tr>
                <!-- <td>{{ response_data['id'] }}</td>
                <td>{{ response_data['username'] }}</td>
                <td>{{ response_data['email'] }}</td>
                <td>{{ response_data['created_at'] }}</td> -->

                <!-- <td>Name</td>
                <td>Number</td>
                <td>Emai</td>
                <td>DDD</td> -->

                <td>{{ response_data['user'].id }}</td>
                <td>{{ response_data['user'].username }}</td>
                <td>{{ response_data['user'].email }}</td>
                <td>{{ response_data['user'].created_at }}</td>
                <td>
                    <button>Review</button>
                    <button onclick="openEditUserForm()">Edit</button>
                    <!-- <button id="delete_{{ user.id }}" onclick="userDelete(this)">Delete</button> -->
                </td>
            </tr>
            <!-- {% endfor %} -->
            <!-- Add more <tr> elements for additional products -->
        </tbody>
    </table>

    <div id="newUserForm" style="display: none;">
        <h3 id="formSection">Add New User</h3>
        <form id="userForm">
            <label for="userName">User Name:</label>
            <input type="text" id="userName" name="userName"><br><br>
            <label for="userEmail">Email:</label>
            <input type="text" id="userEmail" name="userEmail"><br><br>
            <button type="button" onclick="submitForm()">Submit</button>
            <button type="button" onclick="closeNewUserForm()">Cancel</button>
        </form>
    </div>
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <script>
        var form_url = "";
        var form_method = "";
        var base_url = "{{ url_for('users_routes.list_users') }}";
        
        function openNewUserForm() {
            form_method = 'POST';
            form_url = base_url;
            document.getElementById("newUserForm").style.display = "block";
            document.getElementById("formSection").innerHTML = "Add New User";
            document.getElementById("userForm").reset();
        }

        function openEditUserForm(button) {
            var selected_user_id = button.id.split("_")[1];
            form_method = 'PUT';
            form_url = base_url + "/" + selected_userid;

            var name = $('#username'+selected_user_id).html();
            var email = $('#email'+selected_user_id).html();
            var pass = $('#password_'+selected_user_id).html();

            $('#userUsername').val(username);
            $('#userEmail').val(email);
            $('#userPassword').val(password);

            document.getElementById("newUserForm").style.display = "block";
            document.getElementById("formSection").innerHTML = "Edit User";
        }

        function closeNewUserForm() {
            document.getElementById("newUserForm").style.display = "none";
        }

        function submitForm(){
            var request_data = {
                name: $('#userNAme').val(),
                email: $('#UserEmail').val(),
                password: $('#UserPassword'). val()
            }

            $.ajax({
                url: form_url,
                data: request_data,
                method: form_method
            }).done(function(response){
                alert(response.message);
                location.reload();
            })
        }

        function userDelete(button){
            var selected_user_id = button.id.split("_")[1];
            var delete_url = base_url + "/" + selected_user_id

            $.ajax({
                url: delete_url,
                method: "DELETE"
            }).done(function(response){
                alert(response.message);
                location.reload();
            })
        }

        function search(){
            window.location = base_url + '?query=' + $('#searchInput').val();
        }
    </script>
</body>
</html>